(library (chez-python utilities)
  (export string-replace!)
  (import (chezscheme) (chez-python exn))

  (define (string-replace! s f t)
    (unless (string? s)
      (raise-contract-error 'string-replace! "string?" s))
    (unless (char? f)
      (raise-contract-error 'string-replace! "char?" f))
    (unless (char? t)
      (raise-contract-error 'string-replace! "char?" t))
    (let ((sl (string-length s)))
      (let loop ((i 0))
	(if (= i sl)
	    (void)
	    (begin
	      (if (char=? (string-ref s i) f)
		  (string-set! s i t)
		  (void))
	      (loop (+ i 1))))))
    s))
