(library (chez-python utilities)
  (export string-replace! string-split string-prefix string-prefix?)
  (import (chezscheme) (chez-python exn))

  (define (string-replace! s f t)
    (unless (string? s)
      (raise-contract-error 'string-replace! "string?" s))
    (unless (char? f)
      (raise-contract-error 'string-replace! "char?" f))
    (unless (char? t)
      (raise-contract-error 'string-replace! "char?" t))
    (let ((sl (string-length s)))
      (let loop ((i 0))
	(if (= i sl)
	    (void)
	    (begin
	      (if (char=? (string-ref s i) f)
		  (string-set! s i t)
		  (void))
	      (loop (+ i 1))))))
    s)
  (define (string-split s p)
    (unless (string? s)
      (raise-contract-error 'string-split "string?" s))
    (unless (char? p)
      (raise-contract-error 'string-split "char?" p))
    (let ((sl (string-length s)))
      (let loop ((i 0) (sr '()) (r '()))
	(if (= i sl)
	    (reverse (cons (apply string (reverse sr)) r))
	    (let ((c (string-ref s i)))
	      (if (char=? c p)
		  (loop (+ i 1) '() (cons (apply string (reverse sr)) r))
		  (loop (+ i 1) (cons c sr) r)))))))
  (define (string-prefix s pl)
    (unless (string? s)
      (raise-contract-error 'string-prefix "string?" s))
    (unless (list? pl)
      (raise-contract-error 'string-prefix "list?" pl))
    (for-each
     (lambda (p)
       (unless (char? p)
	 (raise-contract-error 'string-prefix "char?" p)))
     pl)
    (let ((sl (string-length s)))
      (let loop ((i 0) (sr '()))
	(if (= i sl)
	    (apply string (reverse sr))
	    (let ((c (string-ref s i)))
	      (if (find (lambda (p) (char=? c p)) pl)
		  (loop (+ i 1) (cons c sr))
		  (apply string (reverse sr))))))))
  (define (string-prefix? s prefix)
    (unless (string? s)
      (raise-contract-error 'string-prefix? "string?" s))
    (unless (string? prefix)
      (raise-contract-error 'string-prefix? "string?" s))
    (and
     (>= (string-length s) (string-length prefix))
     (string=? (substring s 0 (string-length prefix))
	       prefix))))
